In [11]:
import numpy as np
import fractions
import scipy.linalg as la

np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})

np.array([1, 2]) @ np.array([[11/144, 1/144], [1/144, 11/144]]) @ np.array([1, 2]).T

0.40972222222222227

In [12]:
sigma = np.array([[5,3], [3,5]])
la.inv(sigma)

array([[5/16, -3/16],
       [-3/16, 5/16]])

In [32]:
def stac_rozdeleni(P):
    # stacionární rozdělení
    W = np.transpose(P-np.eye(P.shape[0])) 
    pi = la.null_space(W)
    pi = np.transpose(pi/sum(pi)) # normalizace
    print("pi =",pi)
    return pi



In [21]:
P = np.array([[0.1, 0.2, 0.4, 0.3],[0.1, 0.2, 0.4, 0.3],[0.1, 0.2, 0.4, 0.3],[0.1, 0.2, 0.4, 0.3]])
stac_rozdeleni(P)

pi = [[1/10 1/5 2/5 3/10]]


In [22]:
P = np.array([[0.1, 0.2, 0.4, 0.3],[0.1, 0.2, 0.4, 0.3],[0.3, 0.4, 0.3, 0],[0.1, 0.2, 0.4, 0.3]])
stac_rozdeleni(P)

pi = [[19/110 3/11 4/11 21/110]]


In [23]:
P = np.array([[0,0,0,1],[0,0,0.8,0.2],[0,0.8,0.2,0],[0.8,0.2,0,0]])
stac_rozdeleni(P)

pi = [[4/19 5/19 5/19 5/19]]


In [33]:
P = np.array([[0.93, 0.01, 0.02, 0.04, 0,    0,    0],
              [0,    0.94, 0,    0,    0.02, 0.04, 0],
              [0,0,0.95,0,0.01,0, 0.04],
              [0,0,0,0.97,0,0.01,0.02],
              [1,0,0,0,0,0,0,],
              [1,0,0,0,0,0,0],
              [1,0,0,0,0,0,0]])
P2 = P@P
np.sum(P2[0][0:4])
stac_rozdeleni(P) * 1800


pi = [[100/297 50/891 40/297 400/891 1/405 2/297 64/4455]]


array([[20000/33, 10000/99, 8000/33, 80000/99, 40/9, 400/33, 2560/99]])

In [40]:
P = np.array([[1,0,0,0,0],[0.6,0,0.4,0,0],[0,0.6,0,0.4,0],[0,0,0.6,0,0.4],[0,0,0,0,1]])
stac_rozdeleni(P)
P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P@P

pi = [[0 0 0 0 1]
 [1 0 0 0 0]]


array([[1, 0, 0, 0, 0],
       [57/65, 0, 0, 0, 8/65],
       [9/13, 0, 0, 0, 4/13],
       [27/65, 0, 0, 0, 38/65],
       [0, 0, 0, 0, 1]])

In [52]:
T = np.array([[0,0.4, 0], [0.6,0,0.4], [0, 0.6, 0]])
N = la.inv((np.eye(T.shape[0]) - T))
N @ np.array([1,1,1])

array([33/13, 50/13, 43/13])

In [55]:
R = np.array([[0.6, 0], [0, 0], [0, 0.4]])
U = N@R
U

array([[57/65, 8/65],
       [9/13, 4/13],
       [27/65, 38/65]])

In [82]:
Q = np.array([[-2*1/3, 2*1/3, 0], [2/7, -1/3-2/7, 1/3], [0, 2*2/7, -2*2/7]])
pi = la.null_space(Q.T)
pi = np.transpose(pi/sum(pi)) # normalizace
pi
np.eye(3)+2/3*Q
Q

array([[-2/3, 2/3, 0],
       [2/7, -13/21, 1/3],
       [0, 4/7, -4/7]])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [83]:
np.array([[2,0],[0,-1/9],[0,0]]).T

array([[2, 0, 0],
       [0, -1/9, 0]])

In [85]:
Xn = 6+16+12+5+18+5+6+7+15
5+18+15+4+20+3+7+11+16

99