# Markovské řetězce s diskrétním časem

In [1]:
import numpy as np
import scipy.linalg as la

## Příklad 7.1

In [2]:
a = 1/5
b = 3/4

In [3]:
# matice přechodu
P = np.matrix([[1-a,a],[b,1-b]])
print("P =\n", P)

P =
 [[0.8  0.2 ]
 [0.75 0.25]]


In [4]:
print(np.sum(P,axis = 1))

[[1.]
 [1.]]


In [5]:
# dvoukroková matice přechodu
print("P^2 = \n", P**2 )
print(np.sum(P**2,axis = 1))

P^2 = 
 [[0.79   0.21  ]
 [0.7875 0.2125]]
[[1.]
 [1.]]


In [6]:
# počáteční rozdělení
p0 = np.matrix([0,1])
print("p(0) =", p0)

p(0) = [[0 1]]


In [7]:
# rozdělení v čase n
n = 100
pn = p0 * P**n
print("p(n) =",pn)

p(n) = [[0.78947368 0.21052632]]


In [8]:
(15/19, 4/19)

(0.7894736842105263, 0.21052631578947367)

In [9]:
# stacionární rozdělení
W = np.transpose(P-np.eye(P.shape[0])) 
pi = la.null_space(W)
pi = np.transpose(pi/sum(pi)) # normalizace
print("pi =",pi)

pi = [[0.78947368 0.21052632]]


In [10]:
pi*P

matrix([[0.78947368, 0.21052632]])

In [11]:
# pomocí vlastních čísel
D = np.transpose(P)
vl_cis, vl_vec = np.linalg.eig(D)
print(vl_cis)

[1.   0.05]


In [12]:
pi = vl_vec[:,0]
pi = pi/np.sum(pi)
pi = np.transpose(pi)
print(pi)

[[0.78947368 0.21052632]]


In [14]:
def StacDist(P):
    W = np.transpose(P-np.eye(P.shape[0])) 
    pi = la.null_space(W)
    pi = np.transpose(pi/sum(pi))
    return pi

In [15]:
pi = StacDist(P)
print("pi =",pi)

pi = [[0.78947368 0.21052632]]


## Příklad 7.2

In [16]:
P = np.matrix([[0.1, 0.2, 0.4, 0.3],
               [0.1, 0.2, 0.4, 0.3],
               [0.3, 0.4, 0.3, 0],
               [0.1, 0.2, 0.4, 0.3]])
print("P = \n", P)
pi = StacDist(P)
print("pi =",pi)

P = 
 [[0.1 0.2 0.4 0.3]
 [0.1 0.2 0.4 0.3]
 [0.3 0.4 0.3 0. ]
 [0.1 0.2 0.4 0.3]]
pi = [[0.17272727 0.27272727 0.36363636 0.19090909]]


# pokusy

In [3]:
P = np.matrix([[0.25, 0.50, 0.25],
               [0.45, 0.50, 0.05],
               [0.00, 0.90, 0.10]])
print("P = \n", P)
pi = StacDist(P)
print("pi =",pi)

P = 
 [[0.25 0.5  0.25]
 [0.45 0.5  0.05]
 [0.   0.9  0.1 ]]
pi = [[0.32926829 0.54878049 0.12195122]]


In [4]:
pi*82

array([[27., 45., 10.]])